# Generated by Django 4.2.4 on 2023-08-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test', '0002_rename_postid_comment_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
